# Generated by Django 3.0.5 on 2021-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeID', models.IntegerField(primary_key=True, serialize=False)),
                ('nodeType', models.IntegerField()),
                ('nodeLat', models.CharField(max_length=15)),
                ('nodeLng', models.CharField(max_length=15)),
            ],
        ),
    ]
