# Generated by Django 3.0.5 on 2021-05-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridMap',
            fields=[
                ('gridID', models.IntegerField(primary_key=True, serialize=False)),
                ('gridType', models.IntegerField()),
                ('gridLat', models.CharField(max_length=15)),
                ('gridLng', models.CharField(max_length=15)),
                ('gridRow', models.IntegerField()),
                ('gridCol', models.IntegerField()),
            ],
        ),
    ]
